
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package tf.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 36;
  public static final int Let = 2;
  public static final int In = 3;
  public static final int Coma = 29;
  public static final int Llave_c = 43;
  public static final int Double = 13;
  public static final int Llave_a = 42;
  public static final int If = 5;
  public static final int Of = 9;
  public static final int Potencia = 22;
  public static final int Else = 7;
  public static final int Mayor_igual_que = 31;
  public static final int Corchete_c = 45;
  public static final int Corchete_a = 44;
  public static final int Then = 6;
  public static final int Lambda = 39;
  public static final int Division = 20;
  public static final int Int = 12;
  public static final int Menor_igual_que = 33;
  public static final int Parentesis_c = 41;
  public static final int Mayor_que = 30;
  public static final int Flecha_I = 27;
  public static final int Modulo = 21;
  public static final int Parentesis_a = 40;
  public static final int EOF = 0;
  public static final int Flecha_D = 26;
  public static final int And = 35;
  public static final int error = 1;
  public static final int Guarda = 37;
  public static final int Linea = 25;
  public static final int Dolar = 38;
  public static final int Igual_a = 34;
  public static final int Char = 14;
  public static final int ERROR = 46;
  public static final int Case = 8;
  public static final int Menor_que = 32;
  public static final int Identificador = 23;
  public static final int Data = 10;
  public static final int Resta = 18;
  public static final int Type = 11;
  public static final int Bool = 15;
  public static final int Multiplicacion = 19;
  public static final int Where = 4;
  public static final int Numero = 24;
  public static final int Suma = 17;
  public static final int DosPuntos_Doble = 28;
  public static final int Igual = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Let",
  "In",
  "Where",
  "If",
  "Then",
  "Else",
  "Case",
  "Of",
  "Data",
  "Type",
  "Int",
  "Double",
  "Char",
  "Bool",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Modulo",
  "Potencia",
  "Identificador",
  "Numero",
  "Linea",
  "Flecha_D",
  "Flecha_I",
  "DosPuntos_Doble",
  "Coma",
  "Mayor_que",
  "Mayor_igual_que",
  "Menor_que",
  "Menor_igual_que",
  "Igual_a",
  "And",
  "Or",
  "Guarda",
  "Dolar",
  "Lambda",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "ERROR"
  };
}

